### ISSUE TITLE
Would be nice if the site wasn't down

### ISSUE THREAD

**Issue by CharlesSterling** [MicrosoftDocs/learn#12]
Would be nice if the site wasn't down

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de51a00a-3fc8-b95e-f741-d76e3adc4c02
* Version Independent ID: cab58c4d-b26e-8237-c69e-e27f73645cac
* Content: [Hello World interactive tutorial - C# quickstarts](https://docs.microsoft.com/en-us/learn/intro-to-csharp/hello-world?tutorial-step=7)
* Content Source: [learn-pr/intro-to-csharp/hello-world.yml](https://github.com/MicrosoftDocs/learn-pr/blob/live/learn-pr/intro-to-csharp/hello-world.yml)
* Service: **.net**
* GitHub Login: @barlanmsft
* Microsoft Alias: **barlan**

**Comment by barlanmsft** [comment]
Hi @CharlesSterling - could you please provide some additional details? 

- Which page in the Introduction to C# module wasn't working for you?
- What wasn't working on that page? Was text not appearing, was it the C# editor, were you unable to sign in, etc.?

Thanks,
Barry

**Comment by barlanmsft** [comment]
Hi @CharlesSterling - I'm closing this issue for now. If something is still preventing you from accessing our site, please open up a new one and we'll be glad to troubleshoot.
