### ISSUE TITLE
Issue creating service principal in embedded cloud shell

### ISSUE THREAD

**Issue by neilpeterson** [MicrosoftDocs/learn#15]
When running this command in the Learn embedded cloud shell:

```
az ad sp create-for-rbac --query "{ client_id: appId, client_secret: password, tenant_id: tenant }"
```

I recieve the following error:

```
Directory permission is needed for the current user to register the application. For how to configure, please refer 'https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal'. Original error: Insufficient privileges to complete the operation.
```

If I use my local terminal, or cloud shell from the portal, the operation is successful. I've had a co-worker reproduce the issues as well.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca792251-ee93-6b70-447b-87ada3d3550a
* Version Independent ID: 77fb4efa-63ae-92f1-e6d4-5d99c8c94793
* Content: [Create a Packer image of a Linux VM in Azure](https://docs.microsoft.com/en-us/learn/deploy-custom-vmss-app/create-packer-image?tutorial-step=5)
* Content Source: [learn-pr/deploy-custom-vmss-app/create-packer-image.yml](https://github.com/MicrosoftDocs/learn-pr/blob/live/learn-pr/deploy-custom-vmss-app/create-packer-image.yml)
* Service: **azure**
* GitHub Login: @barlanmsft
* Microsoft Alias: **barlan**

**Comment by barlanmsft** [comment]
Hey @neilpeterson - thanks for filing this issue. We've pulled this content down to rework it, so I'll close this for now.
