### ISSUE TITLE
Cosmos DB ID must be all lowercase

### ISSUE THREAD

**Issue by charters** [MicrosoftDocs/learn#16]
Example name given in the tutorial contains capital letters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e931add5-8f69-f7ce-29df-31c3e4abaa96
* Version Independent ID: b0cb60c0-dcf3-75e0-1929-18d9d6e4582e
* Content: [Create an instance of Azure Cosmos DB](https://docs.microsoft.com/en-us/learn/build-serverless-app/create-cosmosdb?tutorial-step=3)
* Content Source: [learn-pr/build-serverless-app/create-cosmosdb.yml](https://github.com/MicrosoftDocs/learn-pr/blob/live/learn-pr/build-serverless-app/create-cosmosdb.yml)
* GitHub Login: @asajohnson
* Microsoft Alias: **asjohnso**

**Comment by barlanmsft** [comment]
Hi @charters - thanks for the feedback. We actually pulled this content down to rework it, but I'll make sure we keep that in mind in future revisions.
