### ISSUE TITLE
Oriental Asian First Names

### ISSUE THREAD

**Issue by sengbinggo** [MicrosoftDocs/learn#8]
My first name is "Seng Bing" not "Seng". How can I make Microsoft's products more Asian/Oriental name friendly?

**Comment by barlanmsft** [comment]
Hi @sengbinggo - for many Microsoft products, you can type two names with a space into the surname/first name field. This could accommodate both Asian and dual Anglophone names like Mary Rose. 

Microsoft offers many ways to submit feedback for products. Here's a few ways to reach out to the product teams for some of Microsoft's most popular products: 

- **Windows** - on a Windows 10 PC, search for **Feedback Hub** to add new feedback or vote on feedback similar to yours. 
- **Office 365** - https://office365.uservoice.com. UserVoice is a similar polling system to Feedback Hub that allows you to vote on feedback and add new pieces of feedback.
- **Xbox** - https://xbox.uservoice.com

Hopefully this helps. For now, I'll close this issue. If you have more specific ones for Tutorials on Microsoft Docs, please feel free to open a new one.

**Comment by sengbinggo** [comment]
![image](https://user-images.githubusercontent.com/39364632/40459834-26530f7a-5f36-11e8-8aa3-b75261b85909.png)


May I know how to close this issue please?
