### ISSUE TITLE
az login

### ISSUE THREAD

**Issue by song1988358** [MicrosoftDocs/learn#9]
az login

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b79db867-e3ec-17fd-671d-671956c57218
* Version Independent ID: 303e4f91-411b-ab3b-c78f-952310b23205
* Content: [Introduction to creating virtual machines with Azure CLI 2.0](https://docs.microsoft.com/zh-cn/learn/azure-cli-2-0/intro?tutorial-step=1)
* Content Source: [learn-pr/azure-cli-2-0/intro.yml](https://github.com/MicrosoftDocs/learn-pr/blob/live/learn-pr/azure-cli-2-0/intro.yml)
* Service: **azure**
* Product: **unspecified**
* GitHub Login: @barlanmsft
* Microsoft Alias: **barlan**

**Comment by barlanmsft** [comment]
hi @song1988358 - are you having a specific issue with the `az login`?

**Comment by barlanmsft** [comment]
Hi @song1988358 - I'm going to close this issue for now. If you have specific questions, please don't hesitate to open another.
